### ISSUE TITLE
A Question about Figure 1 in Paper

### ISSUE THREAD

**Issue by SivilTaram** [LividWo/Perturbed-Masking#1]
Thank you for your interesting and impressive work on interpreting BERT in unsupervised linguistic tasks. I have a small question about Figure 1 in the paper, just as below:

![image](https://user-images.githubusercontent.com/10275209/85246620-b5122b80-b47d-11ea-9a77-9d6bb07fcadb.png)

What is the meaning of each cell, does it mean the *distance* or the *impact*? I understand it should be *impact* since the following sections address that the higher impact represents the closer correlation. However, the right-side color bar ranging from 0 to 5 makes me very confused. So, I'm wondering how to compute the cell using *Dist* or *Prob*? 

Looking forward to your response, thanks :)

**Comment by LividWo** [comment]
In short, each cell **here** depicts the **impact** one word has on the prediction of another. But the impact is calculated using the **Euclidean distance** between two embeddings(_Dist_ method in section 2.2).

Alternatively, if you use the _prob_ method to construct the matrix, the scale of the bar should be something like [-1, 1].

**Comment by SivilTaram** [comment]
@LividWo I just realized that the distance itself is the impact, many thank you for your quick reply!
