### ISSUE TITLE
Could you share the visualization code to reproduce Figure 1? 

### ISSUE THREAD

**Issue by wentinghome** [LividWo/Perturbed-Masking#3]
Hi, 

Could you share the visualization code to reproduce Figure 1 in the paper? 

![1](https://user-images.githubusercontent.com/33013641/85953998-f1400300-b939-11ea-81c3-20a46bbf13cf.png)

Thank you! 

Best,
Wenting

**Comment by LividWo** [comment]
Hi, the code I used to draw this figure is different from the current code base, but you can simply draw a same figure using seaborn's heatmap.

**Comment by SebastiaanJohn** [comment]
Hi. I have been working on reproducing the impact matrix plot from your paper, but I seem to be getting different results compared to the figure presented in your work. I would greatly appreciate your assistance in identifying any steps I might be missing or any potential issues with my approach.

To generate the impact matrices, I executed the following command:

```
python preprocess.py --cuda \
  --probe dependency \
  --data_split PUD \
  --dataset ./dependency/data/PUD.conllu
```

After obtaining the impact matrices, I used the code snippet below to create the plot:

```python
matrix_path = Path("results/dependency/bert-dist-PUD-12.pkl")
with matrix_path.open("rb") as f:
    data = pickle.load(f)
    text, tokens, matrix = data[1]
    print(f"{tokens=}") # tokens=['[CLS]', 'for', 'those', 'who', 'follow', 'social', 'media', 'transitions', 'on', 'capitol', 'hill', ',', 'this', 'will', 'be', 'a', 'little', 'different', '.', '[SEP]']
    print(f"{matrix.shape=}") # matrix.shape=(20, 20)
    sns.heatmap(matrix, xticklabels=tokens, yticklabels=tokens, cmap="crest")
```

However, the resulting plot (attached below) differs from the one presented in your paper.

![image](https://github.com/LividWo/Perturbed-Masking/assets/19330750/7f5aae9b-b664-4d3b-9f3b-fc4d670beb22)

Could you provide any insights or suggestions on what I might be missing or if there are any additional steps or considerations I should take into account to accurately reproduce the impact matrix plot? Thanks!
