### ISSUE TITLE
Help needed to achieve the distance in the ABSC task

### ISSUE THREAD

**Issue by yhcc** [LividWo/Perturbed-Masking#4]
Thanks for publishing your code. 
I am trying to reproduce the results of the ABSC tasks. I used bert-base-uncased to generate the distance of Laptops, but got different distances from your Laptops_Test_Gold.xlm.seg.dist. Since the distance generation does not include random factors (BERT in evaluation mode should always give the same prediction), could you help to achieve the distance as you got in the ABSC folder ? Which layer was you using and metric, etc. ?

**Comment by LividWo** [comment]
Can you report the results with your distance files? They should be close to ours.

The most likely reason is that you forgot to add the inductive bias to favor short dependencies (in paper page 7, bottom left). The details about this idea can be found in https://cs.jhu.edu/~jason/papers/eisner+smith.iwptbook10.pdf. 
I check the code, the default weight is 0, means without this bias. (multiply each cell in the impact matrix with this value before parsing) So I can not remember the exact weight I used, I suggest you try 0.1 first  

We use the last layer(12th) in all our experiments in default. But I am not sure about the ABSC part cause they are separately done.  However, use the last few layers generally perform better(we remove those discussions in camera-ready cause there are some debates between reviewers). So you can also try different layers.

**Comment by yhcc** [comment]
Thanks for your reply. I will try to add the bias. Can i just change the following code to get the bias

https://github.com/LividWo/Perturbed-Masking/blob/f57859261a7daa24de6310ad6ea8cce977d52fde/dependency/dep_parsing.py#L152

to 
```python
best_heads, _ = decoder.parse_proj(final_matrix*0.1)
```
But I guess will not change the results😂, can you provide the code change needed to achieve this bias? Thanks~


I also tried to run your https://github.com/LividWo/Perturbed-Masking/blob/master/ABSC/Laptops_Train.xml.seg.dist directly, the results is 
|| acc | f1 |
|--|--|--|
|My run|74.67|70.58|
|Reported| 75.99 | 72.01 |

Did you change the hyper-parameters in the PCWN code, or used the default one?

**Comment by LividWo** [comment]
My code is very different from those in the repo, but I can give you some tips.

First, you have to get a distance matrix that contains the distance between each pair of words. For example in the sentence "i am coding", the distance between "i" and "coding" is 2. You can either use the absolute distance (like the example) or marginalized the distance by the sentence's length.  My code is as below:
```python
dist_mat = np.zeros(final_matrix.shape)
n = final_matrix.shape[0]
for i, row in enumerate(dist_mat):
      for j, cell in enumerate(row):
            # dist_mat[i, j] = abs(j-i)
            dist_mat[i, j] = 1-abs(j-i)/n
dist_mat = args.local_weight*dist_mat
```
local_weight can be set to 0.1 or other values.

Then after some modification to impact matrix, we multiple each impact value with the corresponding value in the distance matrix(or bias matrix).
```python
for i, row in enumerate(final_matrix):
      for j, cell in enumerate(row):
            final_matrix[i,j] *= dist_mat[i,j]
```
Then you can decode using
```python
best_heads, _ = decoder.parse_proj(final_matrix)
```

**Comment by LividWo** [comment]
For the ABSC experiments, We keep everything in default...Not sure where this discrepancy comes from. I took a look of the results, seems we are using the last layer. Some results as below:
| Laptop        | Acc           | F1  |
| ------------- |:-------------:| -----:|
| layer 12     | 75.23/75.99 | 71.06/72.01 |
| layer 11    | 74.48/75.39   |   69.75/71.56 |
| layer 10 | 75.36/74.61     |   70.88/70.36 |

Each cell contains two results: with and without bias, but I can not remember which one is which 😂

I am busy with paper submission, otherwise, I will take a look of this experiment.

**Comment by yhcc** [comment]
> My code is very different from those in the repo, but I can give you some tips.
> 
> First, you have to get a distance matrix that contains the distance between each pair of words. For example in the sentence "i am coding", the distance between "i" and "coding" is 2. You can either use the absolute distance (like the example) or marginalized the distance by the sentence's length. My code is as below:
> 
> ```python
> dist_mat = np.zeros(final_matrix.shape)
> n = final_matrix.shape[0]
> for i, row in enumerate(dist_mat):
>       for j, cell in enumerate(row):
>             # dist_mat[i, j] = abs(j-i)
>             dist_mat[i, j] = 1-abs(j-i)/n
> dist_mat = args.local_weight*dist_mat
> ```
> 
> local_weight can be set to 0.1 or other values.
> 
> Then after some modification to impact matrix, we multiple each impact value with the corresponding value in the distance matrix(or bias matrix).
> 
> ```python
> for i, row in enumerate(final_matrix):
>       for j, cell in enumerate(row):
>             final_matrix[i,j] *= dist_mat[i,j]
> ```
> 
> Then you can decode using
> 
> ```python
> best_heads, _ = decoder.parse_proj(final_matrix)
> ```

Thanks. I will try this modification.
