### ISSUE TITLE
Why does the "CLS" row of the matrix have very high values on PUD?

### ISSUE THREAD

**Issue by LinkToPast1990** [LividWo/Perturbed-Masking#5]
Hi, @LividWo , thanks for your great work.
I visualized some samples' impact matrix on PUD and found that usually, the "CLS" row has very high values. Any ideas about this phenomenon? Thanks again!

![image](https://user-images.githubusercontent.com/13929748/95727185-6eef0b00-0cac-11eb-9894-e936099b8b09.png)

**Comment by LinkToPast1990** [comment]
The above figure is from './results/dependency/bert-dist-PUD-2.pkl'.
But even using './results/dependency/bert-dist-PUD-12.pkl', those values corresponding to the 'CLS' token are also high.

**Comment by LividWo** [comment]
Just to follow up, have you figure out the reason why this happened?
I cannot find my visualization code to verify this.
I would like to know is this happens more often to lower layers or upper layers?
