### ISSUE TITLE
The results about the left/right in ABSC experiments

### ISSUE THREAD

**Issue by ROGERDJQ** [LividWo/Perturbed-Masking#7]
Thanks for the code publishing. Here comes a issue when I am trying to repro the ABSC part in paper. 
For the ABSC part, the paper use PWCN model and compare the induced tree with the left/right chain additionally. And the left/right get different performance results. However, based on the data pre-processing in PWCN, the left and the right chain should be same. So I am wondering why they two have different output results? or there is some trick  missing  in the paper? 
Expect the reply for this issue, really Thanks.

**Comment by LividWo** [comment]
I think you are correct that the left and right chain tree should produce the same distance vector. 
I checked the two distance file i produced, it looks quite different, for example:
right chain 
```
$T$ is super fast , around anywhere from 35 seconds to 1 minute .
7.5 0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 7.5 7.5 7.5 7.5 7.5 7.5
```
left chain 
```
$T$ is super fast , around anywhere from 35 seconds to 1 minute .
0.0 0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 13.0
```
It looks like the left chain distance is correct, but the right chain is not. 
I cannot find my code for generating this file, so I don't know for sure why this happens.
But my guess, after observing the data, is that I might mis-used the spacy tree as the right-chain tree. 
It would be great if you could share your results afterward.

**Comment by ROGERDJQ** [comment]
Our results are close to your `+left-chain` one yet a little bit smaller.
