### ISSUE TITLE
"Dist" and "Prob" versions

### ISSUE THREAD

**Issue by postylem** [LividWo/Perturbed-Masking#9]
Reading the [paper (section 2.2)](https://aclanthology.org/2020.acl-main.383.pdf), I see the two difference functions
-  "Dist" (Euclidean distance between the embeddings) and 
-  "Prob" (difference in probability of target token)

However, looking at the code, I see the options for the `--metric` flag are
- `dist` (which subtracts and takes norm to get Euclidean distance), https://github.com/LividWo/Perturbed-Masking/blob/f57859261a7daa24de6310ad6ea8cce977d52fde/dependency/get_matrix_for_dep_probe.py#L78-L79 and
- `cos` (which gets cosine similarity) https://github.com/LividWo/Perturbed-Masking/blob/f57859261a7daa24de6310ad6ea8cce977d52fde/dependency/get_matrix_for_dep_probe.py#L80-L82

Is the metric `cos` the "Prob" of the paper?

**Comment by LividWo** [comment]
Hi 
No, it's not.  But won't be difficult to implement by yourself.

**Comment by postylem** [comment]
What did you use to get the result in the paper? I suppose you need a masked LM head on top of the last hidden states of BERT (that is, use a different pretrained model)?

**Comment by LividWo** [comment]
right. you need to obtain the probability rather than the embedding.
